/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PORTMAP_H_RPCGEN
#define _PORTMAP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define PMAP_PORT 111

struct pmap2_mapping {
	u_int prog;
	u_int vers;
	u_int prot;
	u_int port;
};
typedef struct pmap2_mapping pmap2_mapping;

struct pmap2_call_args {
	u_int prog;
	u_int vers;
	u_int proc;
	struct {
		u_int args_len;
		char *args_val;
	} args;
};
typedef struct pmap2_call_args pmap2_call_args;

struct pmap2_call_result {
	u_int port;
	struct {
		u_int res_len;
		char *res_val;
	} res;
};
typedef struct pmap2_call_result pmap2_call_result;

struct pmap2_mapping_list {
	pmap2_mapping map;
	struct pmap2_mapping_list *next;
};
typedef struct pmap2_mapping_list pmap2_mapping_list;

struct pmap2_dump_result {
	struct pmap2_mapping_list *list;
};
typedef struct pmap2_dump_result pmap2_dump_result;

typedef pmap2_mapping PMAP2SETargs;

typedef pmap2_mapping PMAP2UNSETargs;

typedef pmap2_mapping PMAP2GETPORTargs;

typedef pmap2_call_args PMAP2CALLITargs;

typedef pmap2_call_result PMAP2CALLITres;

typedef pmap2_dump_result PMAP2DUMPres;

#define PMAP_PROGRAM 100000
#define PMAP_V2 2

#if defined(__STDC__) || defined(__cplusplus)
#define PMAP2_NULL 0
extern  void * pmap2_null_2(void *, CLIENT *);
extern  void * pmap2_null_2_svc(void *, struct svc_req *);
#define PMAP2_SET 1
extern  uint32_t * pmap2_set_2(PMAP2SETargs *, CLIENT *);
extern  uint32_t * pmap2_set_2_svc(PMAP2SETargs *, struct svc_req *);
#define PMAP2_UNSET 2
extern  uint32_t * pmap2_unset_2(PMAP2UNSETargs *, CLIENT *);
extern  uint32_t * pmap2_unset_2_svc(PMAP2UNSETargs *, struct svc_req *);
#define PMAP2_GETPORT 3
extern  uint32_t * pmap2_getport_2(PMAP2GETPORTargs *, CLIENT *);
extern  uint32_t * pmap2_getport_2_svc(PMAP2GETPORTargs *, struct svc_req *);
#define PMAP2_DUMP 4
extern  PMAP2DUMPres * pmap2_dump_2(void *, CLIENT *);
extern  PMAP2DUMPres * pmap2_dump_2_svc(void *, struct svc_req *);
#define PMAP2_CALLIT 5
extern  PMAP2CALLITres * pmap2_callit_2(PMAP2CALLITargs *, CLIENT *);
extern  PMAP2CALLITres * pmap2_callit_2_svc(PMAP2CALLITargs *, struct svc_req *);
extern int pmap_program_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PMAP2_NULL 0
extern  void * pmap2_null_2();
extern  void * pmap2_null_2_svc();
#define PMAP2_SET 1
extern  uint32_t * pmap2_set_2();
extern  uint32_t * pmap2_set_2_svc();
#define PMAP2_UNSET 2
extern  uint32_t * pmap2_unset_2();
extern  uint32_t * pmap2_unset_2_svc();
#define PMAP2_GETPORT 3
extern  uint32_t * pmap2_getport_2();
extern  uint32_t * pmap2_getport_2_svc();
#define PMAP2_DUMP 4
extern  PMAP2DUMPres * pmap2_dump_2();
extern  PMAP2DUMPres * pmap2_dump_2_svc();
#define PMAP2_CALLIT 5
extern  PMAP2CALLITres * pmap2_callit_2();
extern  PMAP2CALLITres * pmap2_callit_2_svc();
extern int pmap_program_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pmap2_mapping (XDR *, pmap2_mapping*);
extern  bool_t xdr_pmap2_call_args (XDR *, pmap2_call_args*);
extern  bool_t xdr_pmap2_call_result (XDR *, pmap2_call_result*);
extern  bool_t xdr_pmap2_mapping_list (XDR *, pmap2_mapping_list*);
extern  bool_t xdr_pmap2_dump_result (XDR *, pmap2_dump_result*);
extern  bool_t xdr_PMAP2SETargs (XDR *, PMAP2SETargs*);
extern  bool_t xdr_PMAP2UNSETargs (XDR *, PMAP2UNSETargs*);
extern  bool_t xdr_PMAP2GETPORTargs (XDR *, PMAP2GETPORTargs*);
extern  bool_t xdr_PMAP2CALLITargs (XDR *, PMAP2CALLITargs*);
extern  bool_t xdr_PMAP2CALLITres (XDR *, PMAP2CALLITres*);
extern  bool_t xdr_PMAP2DUMPres (XDR *, PMAP2DUMPres*);

#else /* K&R C */
extern bool_t xdr_pmap2_mapping ();
extern bool_t xdr_pmap2_call_args ();
extern bool_t xdr_pmap2_call_result ();
extern bool_t xdr_pmap2_mapping_list ();
extern bool_t xdr_pmap2_dump_result ();
extern bool_t xdr_PMAP2SETargs ();
extern bool_t xdr_PMAP2UNSETargs ();
extern bool_t xdr_PMAP2GETPORTargs ();
extern bool_t xdr_PMAP2CALLITargs ();
extern bool_t xdr_PMAP2CALLITres ();
extern bool_t xdr_PMAP2DUMPres ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PORTMAP_H_RPCGEN */
