/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "portmap.h"

bool_t
xdr_pmap2_mapping (XDR *xdrs, pmap2_mapping *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->prot))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->port))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->prog);
			IXDR_PUT_U_LONG(buf, objp->vers);
			IXDR_PUT_U_LONG(buf, objp->prot);
			IXDR_PUT_U_LONG(buf, objp->port);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->prot))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->port))
				 return FALSE;
		} else {
			objp->prog = IXDR_GET_U_LONG(buf);
			objp->vers = IXDR_GET_U_LONG(buf);
			objp->prot = IXDR_GET_U_LONG(buf);
			objp->port = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->vers))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->prot))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pmap2_call_args (XDR *xdrs, pmap2_call_args *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->proc))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->prog);
		IXDR_PUT_U_LONG(buf, objp->vers);
		IXDR_PUT_U_LONG(buf, objp->proc);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->args.args_val, (u_int *) &objp->args.args_len, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->proc))
				 return FALSE;

		} else {
		objp->prog = IXDR_GET_U_LONG(buf);
		objp->vers = IXDR_GET_U_LONG(buf);
		objp->proc = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->args.args_val, (u_int *) &objp->args.args_len, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->vers))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->proc))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->args.args_val, (u_int *) &objp->args.args_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pmap2_call_result (XDR *xdrs, pmap2_call_result *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->res.res_val, (u_int *) &objp->res.res_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pmap2_mapping_list (XDR *xdrs, pmap2_mapping_list *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_mapping (xdrs, &objp->map))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (pmap2_mapping_list), (xdrproc_t) xdr_pmap2_mapping_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pmap2_dump_result (XDR *xdrs, pmap2_dump_result *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->list, sizeof (pmap2_mapping_list), (xdrproc_t) xdr_pmap2_mapping_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PMAP2SETargs (XDR *xdrs, PMAP2SETargs *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_mapping (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PMAP2UNSETargs (XDR *xdrs, PMAP2UNSETargs *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_mapping (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PMAP2GETPORTargs (XDR *xdrs, PMAP2GETPORTargs *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_mapping (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PMAP2CALLITargs (XDR *xdrs, PMAP2CALLITargs *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_call_args (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PMAP2CALLITres (XDR *xdrs, PMAP2CALLITres *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_call_result (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PMAP2DUMPres (XDR *xdrs, PMAP2DUMPres *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap2_dump_result (xdrs, objp))
		 return FALSE;
	return TRUE;
}
